
  create table "public"."tablefromui" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."tablefromui" enable row level security;

CREATE UNIQUE INDEX tablefromui_pkey ON public.tablefromui USING btree (id);

alter table "public"."tablefromui" add constraint "tablefromui_pkey" PRIMARY KEY using index "tablefromui_pkey";

grant delete on table "public"."tablefromui" to "anon";

grant insert on table "public"."tablefromui" to "anon";

grant references on table "public"."tablefromui" to "anon";

grant select on table "public"."tablefromui" to "anon";

grant trigger on table "public"."tablefromui" to "anon";

grant truncate on table "public"."tablefromui" to "anon";

grant update on table "public"."tablefromui" to "anon";

grant delete on table "public"."tablefromui" to "authenticated";

grant insert on table "public"."tablefromui" to "authenticated";

grant references on table "public"."tablefromui" to "authenticated";

grant select on table "public"."tablefromui" to "authenticated";

grant trigger on table "public"."tablefromui" to "authenticated";

grant truncate on table "public"."tablefromui" to "authenticated";

grant update on table "public"."tablefromui" to "authenticated";

grant delete on table "public"."tablefromui" to "service_role";

grant insert on table "public"."tablefromui" to "service_role";

grant references on table "public"."tablefromui" to "service_role";

grant select on table "public"."tablefromui" to "service_role";

grant trigger on table "public"."tablefromui" to "service_role";

grant truncate on table "public"."tablefromui" to "service_role";

grant update on table "public"."tablefromui" to "service_role";

